# Generated by Django 3.0.6 on 2020-05-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the dataset')),
                ('path', models.CharField(max_length=1024, verbose_name='Path to the dataset')),
                ('segmentations', models.CharField(max_length=1024, verbose_name='Path to the segmentations')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(verbose_name='Label assigned in this annotation')),
                ('seg_id', models.IntegerField(verbose_name='Index of segmentation to which this annotation is linked')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singlecell.Dataset')),
            ],
        ),
    ]
