# Generated by Django 4.0.2 on 2022-02-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlecell', '0004_auto_20200513_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.IntegerField(choices=[(0, 'Bad segmentation'), (1, '1 lobe'), (2, '2 lobes'), (3, '3 lobes'), (4, '4 lobes'), (5, 'Unclear amount of lobes')], default=5, verbose_name='Label assigned in this annotation'),
        ),
    ]
