# Generated by Django 4.0.2 on 2022-02-21 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlecell', '0005_alter_annotation_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='bbox',
            field=models.CharField(default='0,1,1,2', max_length=255, validators=[django.core.validators.int_list_validator], verbose_name='min row, min column, max row, max column'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='scene',
            field=models.CharField(default='scene', max_length=255, verbose_name='CZI Scene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='tile',
            field=models.IntegerField(default=0, verbose_name='Tile within scene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='channel_names',
            field=models.CharField(default=['c1', 'c2'], max_length=255, verbose_name='Comma-separated list of channel names'),
            preserve_default=False,
        ),
    ]
