# Generated by Django 4.0.2 on 2022-02-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlecell', '0006_annotation_bbox_annotation_scene_annotation_tile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.IntegerField(choices=[(-1, 'Not set'), (0, 'Bad segmentation'), (1, '1 lobe'), (2, '2 lobes'), (3, '3 lobes'), (4, '4 lobes'), (5, 'Unclear amount of lobes')], default=-1, verbose_name='Label assigned in this annotation'),
        ),
    ]
